
name: Android Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Check project ZIP
        run: ls -la
